# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlowerApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlowerApp
  pod 'Alamofire'
  pod 'SDWebImage', '~> 5.0'
  pod 'SVProgressHUD'
  pod 'SwiftyJSON', '~> 4.0'	

end
